version: "3.9"
services:
  kenia_db:
    image: postgres:13
    restart: always
    container_name: kenia_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: kenia_db
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev_db

  kenia_api:
    build: .
    container_name: kenia_api
    ports:
      - "80:5500"
    volumes:
      - /usr/app/node_modules
      # - .:/usr/app
    depends_on:
      - kenia_db
